/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_admin4.state;

import hvv_admin4.report.ReportGenerator;
import hvv_admin4.steps.info.TechProcessHvProcessInfo;
import hvv_admin4.steps.info.TechProcessStepCommon;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author yaroslav
 */
public class RestoreHvStep1 extends javax.swing.JDialog {

    final public GregorianCalendar m_gdtmDtmStopActual;
    final public GregorianCalendar m_gdtmDtmParam1;
    final public GregorianCalendar m_gdtmDtmParam2;
    final public GregorianCalendar m_gdtmDtmParam3;
    
    boolean m_bDrop;
    
    /**
     * Creates new form RestoreHvStep
     */
    
    public RestoreHvStep1() {
        initComponents();
        
        paneBlob.setVisible( false);
        
        edtValueParam1.setVisible( false);
        edtValueParam2.setVisible( false);
        edtValueParam3.setVisible( false);
        
        m_gdtmDtmStopActual = new GregorianCalendar( 2018, 1, 10, 22, 0);
        m_gdtmDtmParam1 = new GregorianCalendar( 2018, 1, 10, 22, 0);
        m_gdtmDtmParam2 = new GregorianCalendar( 2018, 1, 10, 22, 0);
        m_gdtmDtmParam3 = new GregorianCalendar( 2018, 1, 10, 22, 0);
        
        /*
        new Timer( 100, new ActionListener() {

            @Override
            public void actionPerformed( ActionEvent e) {
                ( ( Timer) e.getSource()).stop();
                updateData();
                
                //configureAsMessage();
                TechProcessHvProcessInfo info = new TechProcessHvProcessInfo();
                info.SetStartDateAsCurrent( 1);
                info.SetStartReportTitle( "START_REPORT_TITLE");
                info.SetStopDateAsCurrent( 0);
                info.SetStopReportTitle( "STOP_REPORT_TITLE");
                info.SetAnStart( 1.);
                info.SetTuStart( 2.);
                info.SetAnStop(  3.);
                info.SetTuStop(  4.);
                configureAsHv( "FAKE_STEP_NAME", info, 300);
                //configureAsGetterInfo();
                //configureAsIgenIext();
                
            }
        }).start();
        */
        m_bDrop = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleMain = new javax.swing.JLabel();
        lblStepTitle = new javax.swing.JLabel();
        lblStepStartDtmTitle = new javax.swing.JLabel();
        lblStepStartDtmValue = new javax.swing.JLabel();
        lblStepStopDtmTitle = new javax.swing.JLabel();
        lblStepStopDtmValue = new javax.swing.JLabel();
        lblStepStopDtmCalcTitle = new javax.swing.JLabel();
        lblStepStopDtmCalcValue = new javax.swing.JLabel();
        lblStepStopDtmActTitle = new javax.swing.JLabel();
        lblDtmStopActDay = new javax.swing.JLabel();
        lblDtmStopAct_p1 = new javax.swing.JLabel();
        lblDtmStopActMon = new javax.swing.JLabel();
        lblDtmStopAct_p2 = new javax.swing.JLabel();
        lblDtmStopActYear = new javax.swing.JLabel();
        lblDtmStopActHou = new javax.swing.JLabel();
        lblDtmStopAct_p3 = new javax.swing.JLabel();
        lblDtmStopActMin = new javax.swing.JLabel();
        lblTitleStepParam1 = new javax.swing.JLabel();
        edtValueParam1 = new javax.swing.JTextField();
        lblDtmValueDayParam1 = new javax.swing.JLabel();
        lblP1Param1 = new javax.swing.JLabel();
        lblDtmValueMonParam1 = new javax.swing.JLabel();
        lblP2Param1 = new javax.swing.JLabel();
        lblDtmValueYearParam1 = new javax.swing.JLabel();
        lblDtmValueHouParam1 = new javax.swing.JLabel();
        lblP3Param1 = new javax.swing.JLabel();
        lblDtmValueMinParam1 = new javax.swing.JLabel();
        lblTitleStepParam2 = new javax.swing.JLabel();
        edtValueParam2 = new javax.swing.JTextField();
        lblDtmValueDayParam2 = new javax.swing.JLabel();
        lblP1Param2 = new javax.swing.JLabel();
        lblDtmValueMonParam2 = new javax.swing.JLabel();
        lblP2Param2 = new javax.swing.JLabel();
        lblDtmValueYearParam2 = new javax.swing.JLabel();
        lblDtmValueHouParam2 = new javax.swing.JLabel();
        lblP3Param2 = new javax.swing.JLabel();
        lblDtmValueMinParam2 = new javax.swing.JLabel();
        lblTitleStepParam3 = new javax.swing.JLabel();
        edtValueParam3 = new javax.swing.JTextField();
        lblDtmValueDayParam3 = new javax.swing.JLabel();
        lblP1Param3 = new javax.swing.JLabel();
        lblDtmValueMonParam3 = new javax.swing.JLabel();
        lblP2Param3 = new javax.swing.JLabel();
        lblDtmValueYearParam3 = new javax.swing.JLabel();
        lblDtmValueHouParam3 = new javax.swing.JLabel();
        lblP3Param3 = new javax.swing.JLabel();
        lblDtmValueMinParam3 = new javax.swing.JLabel();
        edtValueParam4 = new javax.swing.JTextField();
        lblTitleStepParam4 = new javax.swing.JLabel();
        edtValueParam5 = new javax.swing.JTextField();
        lblTitleStepParam5 = new javax.swing.JLabel();
        edtValueParam6 = new javax.swing.JTextField();
        lblTitleStepParam6 = new javax.swing.JLabel();
        paneBlob = new javax.swing.JScrollPane();
        txtBlob = new javax.swing.JTextArea();
        btnOk = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Восстановление этапа");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setPreferredSize(new java.awt.Dimension(400, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        lblTitleMain.setText("Последний этап отмеченный в файле восстановления:");
        getContentPane().add(lblTitleMain);
        lblTitleMain.setBounds(10, 20, 380, 20);

        lblStepTitle.setText("3.1 Обработка в среде О2-Ne20. 2ой цикл.");
        lblStepTitle.setToolTipText("");
        getContentPane().add(lblStepTitle);
        lblStepTitle.setBounds(10, 40, 380, 20);

        lblStepStartDtmTitle.setText("Дата-время начала:");
        getContentPane().add(lblStepStartDtmTitle);
        lblStepStartDtmTitle.setBounds(10, 70, 180, 20);

        lblStepStartDtmValue.setText("10.01.2018 17:00");
        getContentPane().add(lblStepStartDtmValue);
        lblStepStartDtmValue.setBounds(10, 90, 180, 20);

        lblStepStopDtmTitle.setText("Дата-время завершения:");
        getContentPane().add(lblStepStopDtmTitle);
        lblStepStopDtmTitle.setBounds(200, 70, 180, 20);

        lblStepStopDtmValue.setText("10.01.2018 17:00");
        getContentPane().add(lblStepStopDtmValue);
        lblStepStopDtmValue.setBounds(200, 90, 180, 20);

        lblStepStopDtmCalcTitle.setText("Предположительное время завершения:");
        getContentPane().add(lblStepStopDtmCalcTitle);
        lblStepStopDtmCalcTitle.setBounds(10, 120, 380, 20);

        lblStepStopDtmCalcValue.setText("10.01.2018 17:30");
        getContentPane().add(lblStepStopDtmCalcValue);
        lblStepStopDtmCalcValue.setBounds(10, 140, 380, 20);

        lblStepStopDtmActTitle.setText("Фактическое время завершения:");
        getContentPane().add(lblStepStopDtmActTitle);
        lblStepStopDtmActTitle.setBounds(10, 190, 380, 20);

        lblDtmStopActDay.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmStopActDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmStopActDay.setText("10");
        lblDtmStopActDay.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmStopActDay);
        lblDtmStopActDay.setBounds(10, 210, 50, 30);

        lblDtmStopAct_p1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmStopAct_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmStopAct_p1.setText(".");
        getContentPane().add(lblDtmStopAct_p1);
        lblDtmStopAct_p1.setBounds(60, 210, 10, 30);

        lblDtmStopActMon.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmStopActMon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmStopActMon.setText("01");
        lblDtmStopActMon.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmStopActMon);
        lblDtmStopActMon.setBounds(70, 210, 50, 30);

        lblDtmStopAct_p2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmStopAct_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmStopAct_p2.setText(".");
        getContentPane().add(lblDtmStopAct_p2);
        lblDtmStopAct_p2.setBounds(120, 210, 10, 30);

        lblDtmStopActYear.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmStopActYear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmStopActYear.setText("2018");
        lblDtmStopActYear.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmStopActYear);
        lblDtmStopActYear.setBounds(130, 210, 80, 30);

        lblDtmStopActHou.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmStopActHou.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmStopActHou.setText("17");
        lblDtmStopActHou.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmStopActHou);
        lblDtmStopActHou.setBounds(250, 210, 50, 30);

        lblDtmStopAct_p3.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmStopAct_p3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmStopAct_p3.setText(":");
        getContentPane().add(lblDtmStopAct_p3);
        lblDtmStopAct_p3.setBounds(300, 210, 10, 30);

        lblDtmStopActMin.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmStopActMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmStopActMin.setText("30");
        lblDtmStopActMin.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmStopActMin);
        lblDtmStopActMin.setBounds(310, 210, 50, 30);

        lblTitleStepParam1.setText("Параметр 1");
        getContentPane().add(lblTitleStepParam1);
        lblTitleStepParam1.setBounds(10, 270, 380, 20);
        getContentPane().add(edtValueParam1);
        edtValueParam1.setBounds(10, 290, 380, 30);

        lblDtmValueDayParam1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmValueDayParam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmValueDayParam1.setText("10");
        lblDtmValueDayParam1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmValueDayParam1);
        lblDtmValueDayParam1.setBounds(10, 290, 50, 30);

        lblP1Param1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblP1Param1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblP1Param1.setText(".");
        getContentPane().add(lblP1Param1);
        lblP1Param1.setBounds(60, 290, 10, 30);

        lblDtmValueMonParam1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmValueMonParam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmValueMonParam1.setText("01");
        lblDtmValueMonParam1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmValueMonParam1);
        lblDtmValueMonParam1.setBounds(70, 290, 50, 30);

        lblP2Param1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblP2Param1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblP2Param1.setText(".");
        getContentPane().add(lblP2Param1);
        lblP2Param1.setBounds(120, 290, 10, 30);

        lblDtmValueYearParam1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmValueYearParam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmValueYearParam1.setText("2018");
        lblDtmValueYearParam1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmValueYearParam1);
        lblDtmValueYearParam1.setBounds(130, 290, 80, 30);

        lblDtmValueHouParam1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmValueHouParam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmValueHouParam1.setText("17");
        lblDtmValueHouParam1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmValueHouParam1);
        lblDtmValueHouParam1.setBounds(250, 290, 50, 30);

        lblP3Param1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblP3Param1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblP3Param1.setText(":");
        getContentPane().add(lblP3Param1);
        lblP3Param1.setBounds(300, 290, 10, 30);

        lblDtmValueMinParam1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmValueMinParam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmValueMinParam1.setText("30");
        lblDtmValueMinParam1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmValueMinParam1);
        lblDtmValueMinParam1.setBounds(310, 290, 50, 30);

        lblTitleStepParam2.setText("Параметр 2");
        getContentPane().add(lblTitleStepParam2);
        lblTitleStepParam2.setBounds(10, 330, 380, 20);
        getContentPane().add(edtValueParam2);
        edtValueParam2.setBounds(10, 350, 380, 30);

        lblDtmValueDayParam2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmValueDayParam2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmValueDayParam2.setText("10");
        lblDtmValueDayParam2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmValueDayParam2);
        lblDtmValueDayParam2.setBounds(10, 350, 50, 30);

        lblP1Param2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblP1Param2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblP1Param2.setText(".");
        getContentPane().add(lblP1Param2);
        lblP1Param2.setBounds(60, 350, 10, 30);

        lblDtmValueMonParam2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmValueMonParam2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmValueMonParam2.setText("01");
        lblDtmValueMonParam2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmValueMonParam2);
        lblDtmValueMonParam2.setBounds(70, 350, 50, 30);

        lblP2Param2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblP2Param2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblP2Param2.setText(".");
        getContentPane().add(lblP2Param2);
        lblP2Param2.setBounds(120, 350, 10, 30);

        lblDtmValueYearParam2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmValueYearParam2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmValueYearParam2.setText("2018");
        lblDtmValueYearParam2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmValueYearParam2);
        lblDtmValueYearParam2.setBounds(130, 350, 80, 30);

        lblDtmValueHouParam2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmValueHouParam2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmValueHouParam2.setText("17");
        lblDtmValueHouParam2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmValueHouParam2);
        lblDtmValueHouParam2.setBounds(250, 350, 50, 30);

        lblP3Param2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblP3Param2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblP3Param2.setText(":");
        getContentPane().add(lblP3Param2);
        lblP3Param2.setBounds(300, 350, 10, 30);

        lblDtmValueMinParam2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmValueMinParam2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmValueMinParam2.setText("30");
        lblDtmValueMinParam2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmValueMinParam2);
        lblDtmValueMinParam2.setBounds(310, 350, 50, 30);

        lblTitleStepParam3.setText("Параметр 3");
        getContentPane().add(lblTitleStepParam3);
        lblTitleStepParam3.setBounds(10, 390, 380, 20);
        getContentPane().add(edtValueParam3);
        edtValueParam3.setBounds(10, 410, 380, 30);

        lblDtmValueDayParam3.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmValueDayParam3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmValueDayParam3.setText("10");
        lblDtmValueDayParam3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmValueDayParam3);
        lblDtmValueDayParam3.setBounds(10, 410, 50, 30);

        lblP1Param3.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblP1Param3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblP1Param3.setText(".");
        getContentPane().add(lblP1Param3);
        lblP1Param3.setBounds(60, 410, 10, 30);

        lblDtmValueMonParam3.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmValueMonParam3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmValueMonParam3.setText("01");
        lblDtmValueMonParam3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmValueMonParam3);
        lblDtmValueMonParam3.setBounds(70, 410, 50, 30);

        lblP2Param3.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblP2Param3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblP2Param3.setText(".");
        getContentPane().add(lblP2Param3);
        lblP2Param3.setBounds(120, 410, 10, 30);

        lblDtmValueYearParam3.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmValueYearParam3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmValueYearParam3.setText("2018");
        lblDtmValueYearParam3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmValueYearParam3);
        lblDtmValueYearParam3.setBounds(130, 410, 80, 30);

        lblDtmValueHouParam3.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmValueHouParam3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmValueHouParam3.setText("17");
        lblDtmValueHouParam3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmValueHouParam3);
        lblDtmValueHouParam3.setBounds(250, 410, 50, 30);

        lblP3Param3.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblP3Param3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblP3Param3.setText(":");
        getContentPane().add(lblP3Param3);
        lblP3Param3.setBounds(300, 410, 10, 30);

        lblDtmValueMinParam3.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblDtmValueMinParam3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDtmValueMinParam3.setText("30");
        lblDtmValueMinParam3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lblDtmMouseWheelMoved(evt);
            }
        });
        getContentPane().add(lblDtmValueMinParam3);
        lblDtmValueMinParam3.setBounds(310, 410, 50, 30);
        getContentPane().add(edtValueParam4);
        edtValueParam4.setBounds(10, 470, 380, 30);

        lblTitleStepParam4.setText("Параметр 4");
        getContentPane().add(lblTitleStepParam4);
        lblTitleStepParam4.setBounds(10, 450, 380, 20);
        getContentPane().add(edtValueParam5);
        edtValueParam5.setBounds(10, 530, 380, 30);

        lblTitleStepParam5.setText("Параметр 5");
        getContentPane().add(lblTitleStepParam5);
        lblTitleStepParam5.setBounds(10, 510, 380, 20);
        getContentPane().add(edtValueParam6);
        edtValueParam6.setBounds(10, 590, 380, 30);

        lblTitleStepParam6.setText("Параметр 6");
        getContentPane().add(lblTitleStepParam6);
        lblTitleStepParam6.setBounds(10, 570, 380, 20);

        txtBlob.setColumns(20);
        txtBlob.setRows(5);
        paneBlob.setViewportView(txtBlob);

        getContentPane().add(paneBlob);
        paneBlob.setBounds(10, 292, 380, 330);

        btnOk.setText("Подтвердить и продолжить");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk);
        btnOk.setBounds(10, 630, 380, 40);

        btnDrop.setText("Отменить восстановление");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });
        getContentPane().add(btnDrop);
        btnDrop.setBounds(10, 680, 380, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setVisibleDtmFieldsStopDateTime( boolean bVisible) {
        lblDtmStopActDay.setVisible( bVisible);        lblDtmStopAct_p1.setVisible( bVisible);
        lblDtmStopActMon.setVisible( bVisible);        lblDtmStopAct_p2.setVisible( bVisible);
        lblDtmStopActYear.setVisible( bVisible);
        lblDtmStopActHou.setVisible( bVisible);        lblDtmStopAct_p3.setVisible( bVisible);
        lblDtmStopActMin.setVisible( bVisible);
    }
    
    private void setVisibleDtmFieldsParam1( boolean bVisible) {
        lblDtmValueDayParam1.setVisible( bVisible);    lblP1Param1.setVisible( bVisible);
        lblDtmValueMonParam1.setVisible( bVisible);    lblP2Param1.setVisible( bVisible);
        lblDtmValueYearParam1.setVisible( bVisible);
        lblDtmValueHouParam1.setVisible( bVisible);    lblP3Param1.setVisible( bVisible);
        lblDtmValueMinParam1.setVisible( bVisible);
    }
    
    private void setVisibleDtmFieldsParam2( boolean bVisible) {
        lblDtmValueDayParam2.setVisible( bVisible);    lblP1Param2.setVisible( bVisible);
        lblDtmValueMonParam2.setVisible( bVisible);    lblP2Param2.setVisible( bVisible);
        lblDtmValueYearParam2.setVisible( bVisible);
        lblDtmValueHouParam2.setVisible( bVisible);    lblP3Param2.setVisible( bVisible);
        lblDtmValueMinParam2.setVisible( bVisible);
    }
    
    private void setVisibleDtmFieldsParam3( boolean bVisible) {
        lblDtmValueDayParam3.setVisible( bVisible);    lblP1Param3.setVisible( bVisible);
        lblDtmValueMonParam3.setVisible( bVisible);    lblP2Param3.setVisible( bVisible);
        lblDtmValueYearParam3.setVisible( bVisible);
        lblDtmValueHouParam3.setVisible( bVisible);    lblP3Param3.setVisible( bVisible);
        lblDtmValueMinParam3.setVisible( bVisible);
    }
    
    public void configureAsIgenIext( String strStepTitle) {
        lblStepTitle.setText( strStepTitle);
        
        lblStepStopDtmCalcTitle.setVisible( false);
        lblStepStopDtmCalcValue.setVisible( false);
        
        lblStepStopDtmActTitle.setVisible( false);
        setVisibleDtmFieldsStopDateTime( false);
        
        lblTitleStepParam1.setVisible( true);
        lblTitleStepParam1.setText( "<html>Ток пропадания генерации на аноде</html>");
        setVisibleDtmFieldsParam1( false);
        edtValueParam1.setVisible( true);
        
        lblTitleStepParam2.setVisible( true);
        lblTitleStepParam2.setText( "<html>Ток пропадания генерации на штенгеле</sub></html>");
        setVisibleDtmFieldsParam2( false);
        edtValueParam2.setVisible( true);
        
        lblTitleStepParam3.setVisible( true);
        lblTitleStepParam3.setText( "<html>Ток погасания лазера на аноде</html>");
        setVisibleDtmFieldsParam3( false);
        edtValueParam3.setVisible( true);
        
        lblTitleStepParam4.setVisible( true);
        lblTitleStepParam4.setText( "<html>Ток погасания лазера на штенгеле</html>");
        edtValueParam4.setVisible( true);
        
        lblTitleStepParam5.setVisible( false);
        edtValueParam5.setVisible( false);
        
        lblTitleStepParam6.setVisible( false);
        edtValueParam6.setVisible( false);
        
        paneBlob.setVisible( false);
    }
    
    public void configureAsGetterInfo1( String strStepTitle) {
        lblStepTitle.setText( strStepTitle);
        
        lblTitleStepParam1.setVisible( true);
        lblTitleStepParam1.setText( "<html>Время выброса с геттера при напряжении 4v</sub></html>");
        setVisibleDtmFieldsParam1( true);
        edtValueParam1.setVisible( false);
        
        
        lblTitleStepParam2.setVisible( true);
        lblTitleStepParam2.setText( "<html>Время выброса с геттера при напряжении 9v</sub></html>");
        setVisibleDtmFieldsParam2( true);
        edtValueParam2.setVisible( false);
        
        
        lblTitleStepParam3.setVisible( true);
        lblTitleStepParam3.setText( "<html>Время отключения напряжения 9v</sub></html>");
        setVisibleDtmFieldsParam3( true);
        edtValueParam3.setVisible( false);
        
        lblTitleStepParam4.setVisible( true);
        lblTitleStepParam4.setText( "<html>Величина выброса с геттера при напряжении 4v</html>");
        edtValueParam4.setVisible( true);
        
        lblTitleStepParam5.setVisible( true);
        lblTitleStepParam5.setText( "<html>Величина выброса с геттера при напряжении 9v</html>");
        edtValueParam5.setVisible( true);
        
        lblTitleStepParam6.setVisible( false);
        edtValueParam6.setVisible( false);
        
        paneBlob.setVisible( false);
    }
    
    public void configureAsGetterInfo2( String strStepTitle) {
        lblStepTitle.setText( strStepTitle);
        
        lblTitleStepParam1.setVisible( true);
        lblTitleStepParam1.setText( "<html>Время выброса с геттера при напряжении 4v</sub></html>");
        setVisibleDtmFieldsParam1( true);
        edtValueParam1.setVisible( false);
        
        lblTitleStepParam2.setVisible( true);
        lblTitleStepParam2.setText( "<html>Время выброса с геттера при напряжении 9v</sub></html>");
        setVisibleDtmFieldsParam2( true);
        edtValueParam2.setVisible( false);
        
        lblTitleStepParam3.setVisible( true);
        lblTitleStepParam3.setText( "<html>Величина выброса с геттера при напряжении 4v</html>");
        setVisibleDtmFieldsParam3( false);
        edtValueParam3.setVisible( true);
        
        lblTitleStepParam4.setVisible( true);
        lblTitleStepParam4.setText( "<html>Величина выброса с геттера при напряжении 9v</html>");
        edtValueParam4.setVisible( true);
        
        lblTitleStepParam5.setVisible( false);
        edtValueParam5.setVisible( false);
        
        lblTitleStepParam6.setVisible( false);
        edtValueParam6.setVisible( false);
        
        paneBlob.setVisible( false);
    }
    
    public void configureAsHv( String strStepTitle, TechProcessHvProcessInfo info, int nCalcedDuration) {
        lblStepTitle.setText( strStepTitle);
        
        lblStepStartDtmValue.setText( ReportGenerator.Gen_NiceDate( info.GetStartDate()) + " " +
                                        ReportGenerator.Gen_NiceTime( info.GetStartDate()));
        Date dt_calced = info.GetStartDate();
        dt_calced.setTime( dt_calced.getTime() + nCalcedDuration * 1000);
        lblStepStopDtmCalcValue.setText( ReportGenerator.Gen_NiceDate(dt_calced) + " " +
                                            ReportGenerator.Gen_NiceTime( dt_calced));
        m_gdtmDtmStopActual.setTime( dt_calced);
        
        lblTitleStepParam1.setVisible( true);
        lblTitleStepParam1.setText( "<html>Начало обработки. U<sub>на аноде</sub></html>");
        setVisibleDtmFieldsParam1( false);
        edtValueParam1.setVisible( true);
        edtValueParam1.setText( String.format( "%.0f", info.GetAnStart()));
        
        
        lblTitleStepParam2.setVisible( true);
        lblTitleStepParam2.setText( "<html>Начало обработки. U<sub>на штенгеле</sub></html>");
        setVisibleDtmFieldsParam2( false);
        edtValueParam2.setVisible( true);
        edtValueParam2.setText( String.format( "%.0f", info.GetTuStart()));
        
        
        lblTitleStepParam3.setVisible( true);
        lblTitleStepParam3.setText( "<html>Конец обработки. U<sub>на аноде</sub></html>");
        setVisibleDtmFieldsParam3( false);
        edtValueParam3.setVisible( true);
        edtValueParam3.setText( String.format( "%.0f", info.GetAnStop()));
        
        
        lblTitleStepParam4.setVisible( true);
        lblTitleStepParam4.setText( "<html>Конец обработки. U<sub>на штенгеле</sub></html>");
        edtValueParam4.setVisible( true);
        edtValueParam4.setText( String.format( "%.0f", info.GetTuStop()));
        
        lblTitleStepParam5.setVisible( false);
        edtValueParam5.setVisible( false);
        
        lblTitleStepParam6.setVisible( false);
        edtValueParam6.setVisible( false);
        
        paneBlob.setVisible( false);
        
        updateData();
        /*
        new Timer( 1000, new ActionListener() {

            @Override
            public void actionPerformed( ActionEvent e) {
                ( ( Timer) e.getSource()).stop();
                updateData();
                System.out.println(">>FUCK?");
                System.out.println( e);
            }
        }).start();
        */
    }
    
    public void configureAsCommon( String strStepTitle, TechProcessStepCommon info, int nCalcedDuration) {
        lblStepTitle.setText( strStepTitle);
        
        lblStepStartDtmValue.setText( ReportGenerator.Gen_NiceDate( info.GetStartDate()) + " " +
                                        ReportGenerator.Gen_NiceTime( info.GetStartDate()));
        Date dt_calced = info.GetStartDate();
        dt_calced.setTime( dt_calced.getTime() + nCalcedDuration * 1000);
        lblStepStopDtmCalcValue.setText( ReportGenerator.Gen_NiceDate(dt_calced) + " " +
                                            ReportGenerator.Gen_NiceTime( dt_calced));
        m_gdtmDtmStopActual.setTime( dt_calced);
        
        lblTitleStepParam1.setVisible( false);
        setVisibleDtmFieldsParam1( false);
        edtValueParam1.setVisible( false);
        
        
        lblTitleStepParam2.setVisible( false);
        setVisibleDtmFieldsParam2( false);
        edtValueParam2.setVisible( false);
        
        
        lblTitleStepParam3.setVisible( false);
        setVisibleDtmFieldsParam3( false);
        edtValueParam3.setVisible( false);
        
        
        lblTitleStepParam4.setVisible( false);
        edtValueParam4.setVisible( false);
        
        
        lblTitleStepParam5.setVisible( false);
        edtValueParam5.setVisible( false);
        
        
        lblTitleStepParam6.setVisible( false);
        edtValueParam6.setVisible( false);
        
        paneBlob.setVisible( false);
        
        updateData();
    }
    
    public void configureAsCalcToFinishDtm( String strStepTitle, TechProcessStepCommon info, Date dtNow) {
        lblStepTitle.setText( strStepTitle);
        
        lblStepStartDtmValue.setText( ReportGenerator.Gen_NiceDate( info.GetStartDate()) + " " +
                                        ReportGenerator.Gen_NiceTime( info.GetStartDate()));
        
        lblStepStopDtmCalcValue.setText( ReportGenerator.Gen_NiceDate( dtNow) + " " +
                                            ReportGenerator.Gen_NiceTime( dtNow));
        m_gdtmDtmStopActual.setTime( dtNow);
        
        m_gdtmDtmParam1.setTime( dtNow);
        m_gdtmDtmParam1.add( Calendar.HOUR, 25);
        
        
        lblTitleStepParam1.setVisible( true);
        lblTitleStepParam1.setText( "Дата-время завершения термообезгаживания");
        setVisibleDtmFieldsParam1( true);
        edtValueParam1.setVisible( false);
        
        
        lblTitleStepParam2.setVisible( false);
        setVisibleDtmFieldsParam2( false);
        edtValueParam2.setVisible( false);
        
        
        lblTitleStepParam3.setVisible( false);
        setVisibleDtmFieldsParam3( false);
        edtValueParam3.setVisible( false);
        
        
        lblTitleStepParam4.setVisible( false);
        edtValueParam4.setVisible( false);
        
        
        lblTitleStepParam5.setVisible( false);
        edtValueParam5.setVisible( false);
        
        
        lblTitleStepParam6.setVisible( false);
        edtValueParam6.setVisible( false);
        
        paneBlob.setVisible( false);
        
        updateData();
    }
    
    public void configureAsMessage( String strStepTitle) {
        lblStepTitle.setText( strStepTitle);
        
        lblStepStopDtmCalcTitle.setVisible( false);
        lblStepStopDtmCalcValue.setVisible( false);     
        setVisibleDtmFieldsStopDateTime( false);

        lblTitleStepParam1.setVisible( false);
        setVisibleDtmFieldsParam1( false);
        edtValueParam1.setVisible( false);
        
        lblTitleStepParam2.setVisible( false);
        setVisibleDtmFieldsParam2(false);
        edtValueParam2.setVisible( false);
                
        lblTitleStepParam3.setVisible( false);
        setVisibleDtmFieldsParam3( false);
        edtValueParam3.setVisible( false);
                
        lblTitleStepParam4.setVisible( false);
        edtValueParam4.setVisible( false);
        
        lblTitleStepParam5.setVisible( false);
        edtValueParam5.setVisible( false);
        
        lblTitleStepParam6.setVisible( false);
        edtValueParam6.setVisible( false);
        
        paneBlob.setVisible( true);
    }
    
    private void lblDtmMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lblDtmMouseWheelMoved
        int nSection = GregorianCalendar.SECOND;
        GregorianCalendar clndrToChange = null;
        
        if( evt.getSource().hashCode() == lblDtmStopActDay.hashCode())  { clndrToChange = m_gdtmDtmStopActual; nSection = GregorianCalendar.DAY_OF_MONTH; }
        if( evt.getSource().hashCode() == lblDtmStopActMon.hashCode())  { clndrToChange = m_gdtmDtmStopActual; nSection = GregorianCalendar.MONTH; }
        if( evt.getSource().hashCode() == lblDtmStopActYear.hashCode()) { clndrToChange = m_gdtmDtmStopActual; nSection = GregorianCalendar.YEAR; }
        if( evt.getSource().hashCode() == lblDtmStopActHou.hashCode())  { clndrToChange = m_gdtmDtmStopActual; nSection = GregorianCalendar.HOUR_OF_DAY; }
        if( evt.getSource().hashCode() == lblDtmStopActMin.hashCode())  { clndrToChange = m_gdtmDtmStopActual; nSection = GregorianCalendar.MINUTE; }
        
        if( evt.getSource().hashCode() == lblDtmValueDayParam1.hashCode())  { clndrToChange = m_gdtmDtmParam1; nSection = GregorianCalendar.DAY_OF_MONTH; }
        if( evt.getSource().hashCode() == lblDtmValueMonParam1.hashCode())  { clndrToChange = m_gdtmDtmParam1; nSection = GregorianCalendar.MONTH; }
        if( evt.getSource().hashCode() == lblDtmValueYearParam1.hashCode()) { clndrToChange = m_gdtmDtmParam1; nSection = GregorianCalendar.YEAR; }
        if( evt.getSource().hashCode() == lblDtmValueHouParam1.hashCode())  { clndrToChange = m_gdtmDtmParam1; nSection = GregorianCalendar.HOUR_OF_DAY; }
        if( evt.getSource().hashCode() == lblDtmValueMinParam1.hashCode())  { clndrToChange = m_gdtmDtmParam1; nSection = GregorianCalendar.MINUTE; }
        
        if( evt.getSource().hashCode() == lblDtmValueDayParam2.hashCode())  { clndrToChange = m_gdtmDtmParam2; nSection = GregorianCalendar.DAY_OF_MONTH; }
        if( evt.getSource().hashCode() == lblDtmValueMonParam2.hashCode())  { clndrToChange = m_gdtmDtmParam2; nSection = GregorianCalendar.MONTH; }
        if( evt.getSource().hashCode() == lblDtmValueYearParam2.hashCode()) { clndrToChange = m_gdtmDtmParam2; nSection = GregorianCalendar.YEAR; }
        if( evt.getSource().hashCode() == lblDtmValueHouParam2.hashCode())  { clndrToChange = m_gdtmDtmParam2; nSection = GregorianCalendar.HOUR_OF_DAY; }
        if( evt.getSource().hashCode() == lblDtmValueMinParam2.hashCode())  { clndrToChange = m_gdtmDtmParam2; nSection = GregorianCalendar.MINUTE; }
        
        if( evt.getSource().hashCode() == lblDtmValueDayParam3.hashCode())  { clndrToChange = m_gdtmDtmParam3; nSection = GregorianCalendar.DAY_OF_MONTH; }
        if( evt.getSource().hashCode() == lblDtmValueMonParam3.hashCode())  { clndrToChange = m_gdtmDtmParam3; nSection = GregorianCalendar.MONTH; }
        if( evt.getSource().hashCode() == lblDtmValueYearParam3.hashCode()) { clndrToChange = m_gdtmDtmParam3; nSection = GregorianCalendar.YEAR; }
        if( evt.getSource().hashCode() == lblDtmValueHouParam3.hashCode())  { clndrToChange = m_gdtmDtmParam3; nSection = GregorianCalendar.HOUR_OF_DAY; }
        if( evt.getSource().hashCode() == lblDtmValueMinParam3.hashCode())  { clndrToChange = m_gdtmDtmParam3; nSection = GregorianCalendar.MINUTE; }
        
        if( clndrToChange != null) {
            clndrToChange.add( nSection, -1 * evt.getWheelRotation());
            updateData();
        }
    }//GEN-LAST:event_lblDtmMouseWheelMoved

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        m_bDrop = true;
        dispose();
    }//GEN-LAST:event_btnDropActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        m_bDrop = false;
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    public void updateData() {
        lblDtmStopActDay.setText( ( m_gdtmDtmStopActual.get( Calendar.DAY_OF_MONTH) < 10 ? "0" : "")  + m_gdtmDtmStopActual.get( Calendar.DAY_OF_MONTH));
        lblDtmStopActMon.setText( ( ( m_gdtmDtmStopActual.get( Calendar.MONTH) + 1) < 10 ? "0" : "")       + ( m_gdtmDtmStopActual.get( Calendar.MONTH) + 1));
        lblDtmStopActYear.setText( ( m_gdtmDtmStopActual.get( Calendar.YEAR) < 10 ? "0" : "")       + m_gdtmDtmStopActual.get( Calendar.YEAR));
        lblDtmStopActHou.setText( ( m_gdtmDtmStopActual.get( Calendar.HOUR_OF_DAY) < 10 ? "0" : "") + m_gdtmDtmStopActual.get( Calendar.HOUR_OF_DAY));
        lblDtmStopActMin.setText( ( m_gdtmDtmStopActual.get( Calendar.MINUTE) < 10 ? "0" : "")      + m_gdtmDtmStopActual.get( Calendar.MINUTE));
        
        lblDtmValueDayParam1.setText( ( m_gdtmDtmParam1.get( Calendar.DAY_OF_MONTH) < 10 ? "0" : "")  + m_gdtmDtmParam1.get( Calendar.DAY_OF_MONTH));
        lblDtmValueMonParam1.setText( ( ( m_gdtmDtmParam1.get( Calendar.MONTH) + 1) < 10 ? "0" : "")       + ( m_gdtmDtmParam1.get( Calendar.MONTH) + 1));
        lblDtmValueYearParam1.setText( ( m_gdtmDtmParam1.get( Calendar.YEAR) < 10 ? "0" : "")       + m_gdtmDtmParam1.get( Calendar.YEAR));
        lblDtmValueHouParam1.setText( ( m_gdtmDtmParam1.get( Calendar.HOUR_OF_DAY) < 10 ? "0" : "") + m_gdtmDtmParam1.get( Calendar.HOUR_OF_DAY));
        lblDtmValueMinParam1.setText( ( m_gdtmDtmParam1.get( Calendar.MINUTE) < 10 ? "0" : "")      + m_gdtmDtmParam1.get( Calendar.MINUTE));
        
        lblDtmValueDayParam2.setText( ( m_gdtmDtmParam2.get( Calendar.DAY_OF_MONTH) < 10 ? "0" : "")  + m_gdtmDtmParam2.get( Calendar.DAY_OF_MONTH));
        lblDtmValueMonParam2.setText( ( ( m_gdtmDtmParam2.get( Calendar.MONTH) + 1) < 10 ? "0" : "")       + ( m_gdtmDtmParam2.get( Calendar.MONTH) + 1));
        lblDtmValueYearParam2.setText( ( m_gdtmDtmParam2.get( Calendar.YEAR) < 10 ? "0" : "")       + m_gdtmDtmParam2.get( Calendar.YEAR));
        lblDtmValueHouParam2.setText( ( m_gdtmDtmParam2.get( Calendar.HOUR_OF_DAY) < 10 ? "0" : "") + m_gdtmDtmParam2.get( Calendar.HOUR_OF_DAY));
        lblDtmValueMinParam2.setText( ( m_gdtmDtmParam2.get( Calendar.MINUTE) < 10 ? "0" : "")      + m_gdtmDtmParam2.get( Calendar.MINUTE));
        
        lblDtmValueDayParam3.setText( ( m_gdtmDtmParam3.get( Calendar.DAY_OF_MONTH) < 10 ? "0" : "")  + m_gdtmDtmParam3.get( Calendar.DAY_OF_MONTH));
        lblDtmValueMonParam3.setText( ( ( m_gdtmDtmParam3.get( Calendar.MONTH) + 1) < 10 ? "0" : "")       + ( m_gdtmDtmParam3.get( Calendar.MONTH) + 1));
        lblDtmValueYearParam3.setText( ( m_gdtmDtmParam3.get( Calendar.YEAR) < 10 ? "0" : "")       + m_gdtmDtmParam3.get( Calendar.YEAR));
        lblDtmValueHouParam3.setText( ( m_gdtmDtmParam3.get( Calendar.HOUR_OF_DAY) < 10 ? "0" : "") + m_gdtmDtmParam3.get( Calendar.HOUR_OF_DAY));
        lblDtmValueMinParam3.setText( ( m_gdtmDtmParam3.get( Calendar.MINUTE) < 10 ? "0" : "")      + m_gdtmDtmParam3.get( Calendar.MINUTE));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestoreHvStep1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestoreHvStep1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestoreHvStep1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestoreHvStep1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
                
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestoreHvStep1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnOk;
    public javax.swing.JTextField edtValueParam1;
    public javax.swing.JTextField edtValueParam2;
    public javax.swing.JTextField edtValueParam3;
    public javax.swing.JTextField edtValueParam4;
    public javax.swing.JTextField edtValueParam5;
    public javax.swing.JTextField edtValueParam6;
    private javax.swing.JLabel lblDtmStopActDay;
    private javax.swing.JLabel lblDtmStopActHou;
    private javax.swing.JLabel lblDtmStopActMin;
    private javax.swing.JLabel lblDtmStopActMon;
    private javax.swing.JLabel lblDtmStopActYear;
    private javax.swing.JLabel lblDtmStopAct_p1;
    private javax.swing.JLabel lblDtmStopAct_p2;
    private javax.swing.JLabel lblDtmStopAct_p3;
    private javax.swing.JLabel lblDtmValueDayParam1;
    private javax.swing.JLabel lblDtmValueDayParam2;
    private javax.swing.JLabel lblDtmValueDayParam3;
    private javax.swing.JLabel lblDtmValueHouParam1;
    private javax.swing.JLabel lblDtmValueHouParam2;
    private javax.swing.JLabel lblDtmValueHouParam3;
    private javax.swing.JLabel lblDtmValueMinParam1;
    private javax.swing.JLabel lblDtmValueMinParam2;
    private javax.swing.JLabel lblDtmValueMinParam3;
    private javax.swing.JLabel lblDtmValueMonParam1;
    private javax.swing.JLabel lblDtmValueMonParam2;
    private javax.swing.JLabel lblDtmValueMonParam3;
    private javax.swing.JLabel lblDtmValueYearParam1;
    private javax.swing.JLabel lblDtmValueYearParam2;
    private javax.swing.JLabel lblDtmValueYearParam3;
    private javax.swing.JLabel lblP1Param1;
    private javax.swing.JLabel lblP1Param2;
    private javax.swing.JLabel lblP1Param3;
    private javax.swing.JLabel lblP2Param1;
    private javax.swing.JLabel lblP2Param2;
    private javax.swing.JLabel lblP2Param3;
    private javax.swing.JLabel lblP3Param1;
    private javax.swing.JLabel lblP3Param2;
    private javax.swing.JLabel lblP3Param3;
    private javax.swing.JLabel lblStepStartDtmTitle;
    private javax.swing.JLabel lblStepStartDtmValue;
    private javax.swing.JLabel lblStepStopDtmActTitle;
    private javax.swing.JLabel lblStepStopDtmCalcTitle;
    private javax.swing.JLabel lblStepStopDtmCalcValue;
    private javax.swing.JLabel lblStepStopDtmTitle;
    private javax.swing.JLabel lblStepStopDtmValue;
    private javax.swing.JLabel lblStepTitle;
    private javax.swing.JLabel lblTitleMain;
    private javax.swing.JLabel lblTitleStepParam1;
    private javax.swing.JLabel lblTitleStepParam2;
    private javax.swing.JLabel lblTitleStepParam3;
    private javax.swing.JLabel lblTitleStepParam4;
    private javax.swing.JLabel lblTitleStepParam5;
    private javax.swing.JLabel lblTitleStepParam6;
    public javax.swing.JScrollPane paneBlob;
    public javax.swing.JTextArea txtBlob;
    // End of variables declaration//GEN-END:variables
}
