/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_admin4.state;

/**
 *
 * @author yaroslav
 */
public class RestoreHvStep extends javax.swing.JDialog {

    /**
     * Creates new form RestoreHvStep
     */
    public RestoreHvStep() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStepStartedDtm = new javax.swing.JLabel();
        lblStepStartedDtm1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblStepStartedDtm.setText("<html>... и по рассчётам должен был бы закончиться 2018.09.01 17:00</html>");
        getContentPane().add(lblStepStartedDtm);
        lblStepStartedDtm.setBounds(10, 50, 380, 40);

        lblStepStartedDtm1.setText("<html>Этап \"2.2 Обработка в среде О2. 2ой цикл.\" был начат 2018.01.09 16:30</html>");
        getContentPane().add(lblStepStartedDtm1);
        lblStepStartedDtm1.setBounds(10, 10, 380, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 200, 130, 60);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(120, 130, 130, 60);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(260, 130, 130, 60);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(260, 200, 130, 60);

        jLabel1.setText("<html>U<sub>на штенгеле</sub></html>");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 200, 100, 60);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("В начале");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 110, 130, 15);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("В конце");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 110, 130, 15);

        jLabel4.setText("<html>U<sub>на анод</sub></html>");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 100, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestoreHvStep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestoreHvStep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestoreHvStep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestoreHvStep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestoreHvStep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblStepStartedDtm;
    private javax.swing.JLabel lblStepStartedDtm1;
    // End of variables declaration//GEN-END:variables
}
