/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_admin4.panels;

import hvv_admin4.HVV_Admin4;
import hvv_admin4.steps.info.TechProcessCommentInfo;
import hvv_admin4.steps.info.TechProcessStepCommon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import org.apache.log4j.Logger;

/**
 *
 * @author yaroslav
 */
public class PanelEnterComment extends javax.swing.JPanel {
    final HVV_Admin4 theApp;
    static Logger logger = Logger.getLogger(PanelEnterComment.class);
    
    /**
     * Creates new form PanelProcess
     */
    public PanelEnterComment( HVV_Admin4 app) {
        theApp = app;
        
        initComponents();
        
    }

    public void InitComponentsOnStart( String strComment) {
        switch( theApp.GetCurrentStep()) {
            case 82:
                lblTitle.setText( "<html><u>5.2 Внесение промежуточных комментариев.</u></html>");
                btnOkNext.setText( "Прибор годен. Продолжаем процесс обработки.");
                btnFailStop.setText( "Прибор будет снят и отправлен на переборку. Останавливаем процесс обработки.");
            break;
            case 184:
                lblTitle.setText( "<html><u>10.4 Внесение итоговых комментариев.</u></html>");
                btnOkNext.setText( "Прибор годен. Перейти к герметизации.");
                //btnFailStop.setText( "Прибор будет снят и отправлен на переборку.");
                btnFailStop.setVisible( false);
                btnOkNext.setSize( btnOkNext.getSize().width, btnOkNext.getHeight()+ btnFailStop.getHeight() + 10);
            break;
        }
        
        if( strComment != null) {
            edtComment.setText( strComment);
        }
        
        btnOkNext.setEnabled( false);
        btnFailStop.setEnabled( false);
        new  Timer( 1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                (( Timer) e.getSource()).stop();
                btnOkNext.setEnabled( true);
                btnFailStop.setEnabled( true);
            }
        }).start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGetter = new javax.swing.ButtonGroup();
        btnGroupSize = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblSerial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtComment = new javax.swing.JTextArea();
        btnOkNext = new javax.swing.JButton();
        btnFailStop = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 200)));
        setMaximumSize(new java.awt.Dimension(640, 440));
        setMinimumSize(new java.awt.Dimension(640, 440));
        setPreferredSize(new java.awt.Dimension(640, 440));
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("<html><u>5.2 Внесение комментариев.</u></html>");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        add(lblTitle);
        lblTitle.setBounds(10, 10, 620, 40);

        lblSerial.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lblSerial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSerial.setText("<html>Введите комментарий по результату измерения промежуточных параметров:</html>");
        lblSerial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        add(lblSerial);
        lblSerial.setBounds(10, 60, 620, 50);

        edtComment.setColumns(20);
        edtComment.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        edtComment.setRows(5);
        jScrollPane1.setViewportView(edtComment);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 620, 190);

        btnOkNext.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        btnOkNext.setText("Прибор годен. Продолжаем процесс обработки.");
        btnOkNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkNextActionPerformed(evt);
            }
        });
        add(btnOkNext);
        btnOkNext.setBounds(10, 320, 620, 50);

        btnFailStop.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        btnFailStop.setText("Прибор будет снят и отправлен на переборку. Останавливаем процесс обработки.");
        btnFailStop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFailStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFailStopActionPerformed(evt);
            }
        });
        add(btnFailStop);
        btnFailStop.setBounds(10, 380, 620, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkNextActionPerformed
        
        TechProcessCommentInfo info = ( TechProcessCommentInfo) theApp.GetCommonStep( String.format( "%03d", theApp.GetCurrentStep()));
        info.m_strComment = edtComment.getText();
        info.SetStopDateAsCurrent( theApp.GetSettings().GetTimeZoneShift());
        info.SetStopReportTitle( "");
        
        switch( theApp.GetCurrentStep()) {
            case 83:
                theApp.SetCurrentStep( 101);
                theApp.SetCurrentStepInProgress( false);
                
                theApp.m_pMainWnd.m_pnlMain.m_pnlProcess.m_pnlStep05.m_bCollapsed = true;
                theApp.m_pMainWnd.m_pnlMain.m_pnlProcess.SetStates();
                theApp.m_pMainWnd.m_pnlMain.m_pnlProcess.Reposition();
                theApp.m_pMainWnd.m_pnlMain.ScrollActiveStepToCenter();
                
                theApp.m_pMainWnd.m_pnlMain.setVisible( true);
                theApp.m_pMainWnd.m_pnlEnterComment.setVisible( false);
            break;
            case 184:
                theApp.SetCurrentStep( 185);
                theApp.SetCurrentStepInProgress( false);
                
                theApp.m_pMainWnd.m_pnlFinalMessage.Init();
                theApp.m_pMainWnd.m_pnlFinalMessage.setVisible( true);
                theApp.m_pMainWnd.m_pnlEnterComment.setVisible( false);
            break;
        }
        
        theApp.m_pStateKeeper.SaveState();
        theApp.m_ReportGenerator.Generate();
        
    }//GEN-LAST:event_btnOkNextActionPerformed

    private void btnFailStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFailStopActionPerformed
        TechProcessCommentInfo info = ( TechProcessCommentInfo) theApp.GetCommonStep( String.format( "%03d", theApp.GetCurrentStep()));
        info.m_strComment = edtComment.getText();
        info.SetStopDateAsCurrent( theApp.GetSettings().GetTimeZoneShift());
        info.SetStopReportTitle( "");
        
        theApp.SetFailInMiddleFlag( true);
                
        switch( theApp.GetCurrentStep()) {
            case 83:
                theApp.SetCurrentStep( 101);
                theApp.SetCurrentStepInProgress( false);
                
                theApp.m_pMainWnd.m_pnlMain.m_pnlProcess.m_pnlStep05.m_bCollapsed = true;
                theApp.m_pMainWnd.m_pnlMain.m_pnlProcess.SetStates();
                theApp.m_pMainWnd.m_pnlMain.m_pnlProcess.Reposition();
                theApp.m_pMainWnd.m_pnlMain.ScrollActiveStepToCenter();
                
                theApp.m_pMainWnd.m_pnlMain.setVisible( true);
                theApp.m_pMainWnd.m_pnlEnterComment.setVisible( false);
            break;
            case 184:
                theApp.SetCurrentStep( 185);
                theApp.SetCurrentStepInProgress( false);
                
                theApp.m_pMainWnd.m_pnlFinalMessage.Init();
                theApp.m_pMainWnd.m_pnlFinalMessage.setVisible( true);
                theApp.m_pMainWnd.m_pnlEnterComment.setVisible( false);
            break;
        }
        
        theApp.m_ReportGenerator.Generate();
        
        System.exit( 0);
        //theApp.m_pMainWnd.dispose();
    }//GEN-LAST:event_btnFailStopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFailStop;
    private javax.swing.ButtonGroup btnGroupGetter;
    private javax.swing.ButtonGroup btnGroupSize;
    private javax.swing.JButton btnOkNext;
    private javax.swing.JTextArea edtComment;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSerial;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
