/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_admin4.panels;

import hvv_admin4.HVV_Admin4;
import hvv_admin4.steps.info.TechProcessStepCommon;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Action;
import javax.swing.Timer;
import org.apache.log4j.Logger;

/**
 *
 * @author yaroslav
 */
public class PanelMessage extends javax.swing.JPanel {
    final HVV_Admin4 theApp;
    static Logger logger = Logger.getLogger(PanelMessage.class);
    public long m_lTimer;
    public int m_nFlasher;
    Timer m_pTimer;
    /**
     * Creates new form PanelProcess
     */
    public PanelMessage( HVV_Admin4 app) {
        theApp = app;
        initComponents();
    }

    public void Init() {
        switch( theApp.GetCurrentStep()) {
            case 185:
                lblTitle.setText( "<html><u>10.5 Завершение процесса э/в обработки.</u></html>");
            break;
            default: lblTitle.setText( "What's happ?!"); break;
        }
        
        btnFinish.setEnabled( false);
        new  Timer( 2000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                (( Timer) e.getSource()).stop();
                btnFinish.setEnabled( true);
            }
        }).start();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnFinish = new javax.swing.JButton();
        lblStart = new javax.swing.JLabel();
        lblStart1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 200)));
        setMaximumSize(new java.awt.Dimension(640, 440));
        setMinimumSize(new java.awt.Dimension(640, 440));
        setPreferredSize(new java.awt.Dimension(640, 440));
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("<html><u>10.5 Завершение процесса э/в обработки.</u></html>");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        add(lblTitle);
        lblTitle.setBounds(10, 10, 620, 40);

        btnFinish.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        btnFinish.setText("Завершение обработки");
        btnFinish.setEnabled(false);
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });
        add(btnFinish);
        btnFinish.setBounds(20, 300, 600, 120);

        lblStart.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lblStart.setText("<html>Проведите герметизацию.</html>");
        add(lblStart);
        lblStart.setBounds(20, 70, 600, 110);

        lblStart1.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblStart1.setText("<html>По завершению герметизации, выключите геттер.</html>");
        add(lblStart1);
        lblStart1.setBounds(20, 180, 600, 110);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        TechProcessStepCommon info = new TechProcessStepCommon( theApp);
        info.SetStartDateAsCurrent();
        info.SetStartReportTitle( "Завершение процесса э/в обработки");
        theApp.SaveStepInfo( "185", info, false);
        
        theApp.SetCurrentStep( 186);
        theApp.m_ReportGenerator.Generate();
        
        theApp.m_pMainWnd.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnFinishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinish;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblStart1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
