/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hvv_admin4.panels;

import hvv_admin4.HVV_Admin4;
import hvv_admin4.HVV_Admin4Constants;
import hvv_admin4.steps.info.TechProcessCommentInfo;
import hvv_admin4.steps.info.TechProcessIgenIextProcessInfo;
import hvv_admin4.steps.info.TechProcessUacProcessInfo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import org.apache.log4j.Logger;

/**
 *
 * @author yaroslav
 */
public class PanelEnterCVC extends javax.swing.JPanel {
    final HVV_Admin4 theApp;
    static Logger logger = Logger.getLogger(PanelEnterCVC.class);
    final private double m_dbl_AUCoefficient_10, m_dbl_AUCoefficient_11, m_dbl_AUCoefficient_12;
    final private double m_dbl_TUCoefficient_10, m_dbl_TUCoefficient_11, m_dbl_TUCoefficient_12;
    
    /**
     * Creates new form PanelProcess
     */
    public PanelEnterCVC( HVV_Admin4 app) {
        theApp = app;
        initComponents();
        
        btn1000mcA.setVisible( false);
        btn1100mcA.setVisible( false);
        btn1200mcA.setVisible( false);
        
        switch( theApp.GetSelectedArm()) {
            case HVV_Admin4Constants.ARM1:
                m_dbl_AUCoefficient_10 = 1.1977;  m_dbl_AUCoefficient_11 = 1.1950;  m_dbl_AUCoefficient_12 = 1.1948;
                m_dbl_TUCoefficient_10 = 0.9873;  m_dbl_TUCoefficient_11 = 0.98895; m_dbl_TUCoefficient_12 = 0.98699;
            break;
            
            case HVV_Admin4Constants.ARM2:
                m_dbl_AUCoefficient_10 = 0.9909;  m_dbl_AUCoefficient_11 = 0.9889;  m_dbl_AUCoefficient_12 = 0.9907;
                m_dbl_TUCoefficient_10 = 0.9873;  m_dbl_TUCoefficient_11 = 0.9871;  m_dbl_TUCoefficient_12 = 0.98696;
            break;
                
            case HVV_Admin4Constants.ARM3:
                m_dbl_AUCoefficient_10 = 0.99269; m_dbl_AUCoefficient_11 = 0.99259; m_dbl_AUCoefficient_12 = 0.9925;
                m_dbl_TUCoefficient_10 = 0.99267; m_dbl_TUCoefficient_11 = 0.99259; m_dbl_TUCoefficient_12 = 0.9906;
            break;
                
            case HVV_Admin4Constants.ARM4:
                m_dbl_AUCoefficient_10 = 0.9873;  m_dbl_AUCoefficient_11 = 0.9872;   m_dbl_AUCoefficient_12 = 0.9870;
                m_dbl_TUCoefficient_10 = 0.9873;  m_dbl_TUCoefficient_11 = 0.9871;   m_dbl_TUCoefficient_12 = 0.9870;
            break;
                
            default:
                m_dbl_AUCoefficient_10 = 1.; m_dbl_AUCoefficient_11 = 1.; m_dbl_AUCoefficient_12 = 1.;
                m_dbl_TUCoefficient_10 = 1.; m_dbl_TUCoefficient_11 = 1.; m_dbl_TUCoefficient_12 = 1.;
        }
    }

    public void InitComponentsOnStart() {
        switch( theApp.GetCurrentStep()) {
            case 82:
                lblTitle.setText( "<html><u>5.2 Замеры параметров. ВАХ.</u></html>");
            break;
            case 183:
                lblTitle.setText( "<html><u>10.3 Замеры параметров. ВАХ.</u></html>");
            break;
        }
        
        edt1000mcA_UA.setText( "");
        lblValueUa1000.setText( "0 V");
        edt1000mcA_UT.setText(  "");
        lblValueUt1000.setText( "0 V");
        
        edt1100mcA_UA.setText( "");
        lblValueUa1100.setText( "0 V");
        edt1100mcA_UT.setText(  "");
        lblValueUt1100.setText( "0 V");
        
        edt1200mcA_UA.setText( "");
        lblValueUa1200.setText( "0 V");
        edt1200mcA_UT.setText(  "");
        lblValueUt1200.setText( "0 V");
        
        btnNext.setEnabled( false);
        new  Timer( 1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                (( Timer) e.getSource()).stop();
                btnNext.setEnabled( true);
            }
        }).start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTitleUanode = new javax.swing.JLabel();
        lblTitleUtubulation = new javax.swing.JLabel();
        lblTitle1000mcA = new javax.swing.JLabel();
        edt1000mcA_UA = new javax.swing.JTextField();
        lblEquUa1000 = new javax.swing.JLabel();
        lblValueUa1000 = new javax.swing.JLabel();
        edt1000mcA_UT = new javax.swing.JTextField();
        lblEquUt1000 = new javax.swing.JLabel();
        lblValueUt1000 = new javax.swing.JLabel();
        lblTitle1100mcA = new javax.swing.JLabel();
        edt1100mcA_UA = new javax.swing.JTextField();
        lblEquUa1100 = new javax.swing.JLabel();
        lblValueUa1100 = new javax.swing.JLabel();
        edt1100mcA_UT = new javax.swing.JTextField();
        lblEquUt1100 = new javax.swing.JLabel();
        lblValueUt1100 = new javax.swing.JLabel();
        lblTitle1200mcA = new javax.swing.JLabel();
        edt1200mcA_UA = new javax.swing.JTextField();
        lblEquUa1200 = new javax.swing.JLabel();
        lblValueUa1200 = new javax.swing.JLabel();
        edt1200mcA_UT = new javax.swing.JTextField();
        lblEquUt1200 = new javax.swing.JLabel();
        lblValueUt1200 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btn1000mcA = new javax.swing.JButton();
        btn1100mcA = new javax.swing.JButton();
        btn1200mcA = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 200)));
        setMaximumSize(new java.awt.Dimension(520, 440));
        setMinimumSize(new java.awt.Dimension(520, 440));
        setPreferredSize(new java.awt.Dimension(520, 440));
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle.setText("<html><u>5.1 Замеры параметров. ВАХ.</u></html>");
        add(lblTitle);
        lblTitle.setBounds(10, 10, 500, 40);

        lblTitleUanode.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lblTitleUanode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleUanode.setText("<html>U<sub> на аноде</sub></html>");
        add(lblTitleUanode);
        lblTitleUanode.setBounds(90, 60, 210, 40);

        lblTitleUtubulation.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lblTitleUtubulation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleUtubulation.setText("<html>U<sub> на штенгеле</sub></html>");
        add(lblTitleUtubulation);
        lblTitleUtubulation.setBounds(300, 60, 210, 40);

        lblTitle1000mcA.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lblTitle1000mcA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1000mcA.setText("<html>1.0 мА</html>");
        add(lblTitle1000mcA);
        lblTitle1000mcA.setBounds(10, 110, 70, 80);

        edt1000mcA_UA.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        edt1000mcA_UA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edt1000mcA_UA.setNextFocusableComponent(edt1100mcA_UA);
        edt1000mcA_UA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edt1000mcA_UAKeyReleased(evt);
            }
        });
        add(edt1000mcA_UA);
        edt1000mcA_UA.setBounds(90, 110, 100, 80);

        lblEquUa1000.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        lblEquUa1000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEquUa1000.setText("=");
        add(lblEquUa1000);
        lblEquUa1000.setBounds(190, 110, 30, 80);

        lblValueUa1000.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        lblValueUa1000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValueUa1000.setText("0 V");
        add(lblValueUa1000);
        lblValueUa1000.setBounds(220, 110, 80, 80);

        edt1000mcA_UT.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        edt1000mcA_UT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edt1000mcA_UT.setNextFocusableComponent(edt1100mcA_UT);
        edt1000mcA_UT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edt1000mcA_UTKeyReleased(evt);
            }
        });
        add(edt1000mcA_UT);
        edt1000mcA_UT.setBounds(300, 110, 100, 80);

        lblEquUt1000.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        lblEquUt1000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEquUt1000.setText("=");
        add(lblEquUt1000);
        lblEquUt1000.setBounds(400, 110, 30, 80);

        lblValueUt1000.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        lblValueUt1000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValueUt1000.setText("0 V");
        add(lblValueUt1000);
        lblValueUt1000.setBounds(430, 110, 80, 80);

        lblTitle1100mcA.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lblTitle1100mcA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1100mcA.setText("<html>1.1 мА</html>");
        add(lblTitle1100mcA);
        lblTitle1100mcA.setBounds(10, 200, 70, 80);

        edt1100mcA_UA.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        edt1100mcA_UA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edt1100mcA_UA.setNextFocusableComponent(edt1200mcA_UA);
        edt1100mcA_UA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edt1100mcA_UAKeyReleased(evt);
            }
        });
        add(edt1100mcA_UA);
        edt1100mcA_UA.setBounds(90, 200, 100, 80);

        lblEquUa1100.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        lblEquUa1100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEquUa1100.setText("=");
        add(lblEquUa1100);
        lblEquUa1100.setBounds(190, 200, 30, 80);

        lblValueUa1100.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        lblValueUa1100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValueUa1100.setText("0 V");
        add(lblValueUa1100);
        lblValueUa1100.setBounds(220, 200, 80, 80);

        edt1100mcA_UT.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        edt1100mcA_UT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edt1100mcA_UT.setNextFocusableComponent(edt1200mcA_UT);
        edt1100mcA_UT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edt1100mcA_UTKeyReleased(evt);
            }
        });
        add(edt1100mcA_UT);
        edt1100mcA_UT.setBounds(300, 200, 100, 80);

        lblEquUt1100.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        lblEquUt1100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEquUt1100.setText("=");
        add(lblEquUt1100);
        lblEquUt1100.setBounds(400, 200, 30, 80);

        lblValueUt1100.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        lblValueUt1100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValueUt1100.setText("0 V");
        add(lblValueUt1100);
        lblValueUt1100.setBounds(430, 200, 80, 80);

        lblTitle1200mcA.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lblTitle1200mcA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1200mcA.setText("1.2 мА");
        add(lblTitle1200mcA);
        lblTitle1200mcA.setBounds(10, 290, 70, 80);

        edt1200mcA_UA.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        edt1200mcA_UA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edt1200mcA_UA.setNextFocusableComponent(edt1000mcA_UT);
        edt1200mcA_UA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edt1200mcA_UAKeyReleased(evt);
            }
        });
        add(edt1200mcA_UA);
        edt1200mcA_UA.setBounds(90, 290, 100, 80);

        lblEquUa1200.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        lblEquUa1200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEquUa1200.setText("=");
        add(lblEquUa1200);
        lblEquUa1200.setBounds(190, 290, 30, 80);

        lblValueUa1200.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        lblValueUa1200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValueUa1200.setText("0 V");
        add(lblValueUa1200);
        lblValueUa1200.setBounds(220, 290, 80, 80);

        edt1200mcA_UT.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        edt1200mcA_UT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edt1200mcA_UT.setNextFocusableComponent(btnNext);
        edt1200mcA_UT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edt1200mcA_UTKeyReleased(evt);
            }
        });
        add(edt1200mcA_UT);
        edt1200mcA_UT.setBounds(300, 290, 100, 80);

        lblEquUt1200.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        lblEquUt1200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEquUt1200.setText("=");
        add(lblEquUt1200);
        lblEquUt1200.setBounds(400, 290, 30, 80);

        lblValueUt1200.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        lblValueUt1200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValueUt1200.setText("0 V");
        add(lblValueUt1200);
        lblValueUt1200.setBounds(430, 290, 80, 80);

        btnNext.setText("Далее");
        btnNext.setNextFocusableComponent(edt1000mcA_UA);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        add(btnNext);
        btnNext.setBounds(10, 380, 500, 50);

        btn1000mcA.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        btn1000mcA.setText("1.0 мА");
        add(btn1000mcA);
        btn1000mcA.setBounds(10, 290, 70, 80);

        btn1100mcA.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        btn1100mcA.setText("1.0 мА");
        add(btn1100mcA);
        btn1100mcA.setBounds(10, 200, 70, 80);

        btn1200mcA.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        btn1200mcA.setText("1.0 мА");
        add(btn1200mcA);
        btn1200mcA.setBounds(10, 110, 70, 80);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        
        TechProcessUacProcessInfo info = ( TechProcessUacProcessInfo)
                theApp.GetCommonStep( String.format( "%03d", theApp.GetCurrentStep()));
        info.SetStopDateAsCurrent( theApp.GetSettings().GetTimeZoneShift());
        //info.SetStopReportTitle( "");
        
        try {
            //String strVal;
            //double dblVal;
            
            //strVal = lblValueUa1000.getText();
            //strVal.trim( " V");
            
            info.Set_1000_A( new Double( lblValueUa1000.getText().replaceAll(" V", "")));
            info.Set_1000_T( new Double( lblValueUt1000.getText().replaceAll(" V", "")));
            info.Set_1100_A( new Double( lblValueUa1100.getText().replaceAll(" V", "")));
            info.Set_1100_T( new Double( lblValueUt1100.getText().replaceAll(" V", "")));
            info.Set_1200_A( new Double( lblValueUa1200.getText().replaceAll(" V", "")));
            info.Set_1200_T( new Double( lblValueUt1200.getText().replaceAll(" V", "")));
        }
        catch( NumberFormatException ex) {
            logger.warn( "На этапе вводе чисел ВАХ, поймали NumberFormatException", ex);
            return;
        }
        
        theApp.SetCurrentStep( theApp.GetCurrentStep() + 1);
        
        
        TechProcessCommentInfo info2 = new TechProcessCommentInfo();
        info2.SetStartDateAsCurrent( theApp.GetSettings().GetTimeZoneShift());
        if( theApp.GetCurrentStep() == 83)
            info2.SetStartReportTitle( "Промежуточный комментарий");
        else
            info2.SetStartReportTitle( "Итоговый комментарий");
        
        theApp.SaveStepInfo( String.format( "%03d", theApp.GetCurrentStep()), info2, true);
        
        
        theApp.SetCurrentStepInProgress( true);
        
        theApp.m_pMainWnd.m_pnlEnterComment.InitComponentsOnStart( null);
        theApp.m_pMainWnd.m_pnlEnterComment.setVisible( true);

        theApp.m_pMainWnd.m_pnlEnterCVC.setVisible( false);
    }//GEN-LAST:event_btnNextActionPerformed
    
    private void edt1000mcA_UAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edt1000mcA_UAKeyReleased
        int nVal = 0;
        String strTyped = edt1000mcA_UA.getText();
        try { nVal = Integer.parseInt( strTyped); }
        catch( NumberFormatException ex) {  }
        lblValueUa1000.setText( String.format( "%.0f V", m_dbl_AUCoefficient_10 * nVal));
    }//GEN-LAST:event_edt1000mcA_UAKeyReleased

    private void edt1000mcA_UTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edt1000mcA_UTKeyReleased
        int nVal = 0;
        String strTyped = edt1000mcA_UT.getText();
        try { nVal = Integer.parseInt( strTyped); }
        catch( NumberFormatException ex) {  }
        lblValueUt1000.setText( String.format( "%.0f V", m_dbl_TUCoefficient_10 * nVal));
    }//GEN-LAST:event_edt1000mcA_UTKeyReleased

    private void edt1100mcA_UAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edt1100mcA_UAKeyReleased
        int nVal = 0;
        String strTyped = edt1100mcA_UA.getText();
        try { nVal = Integer.parseInt( strTyped); }
        catch( NumberFormatException ex) {  }
        lblValueUa1100.setText( String.format( "%.0f V", m_dbl_AUCoefficient_11 * nVal));
    }//GEN-LAST:event_edt1100mcA_UAKeyReleased

    private void edt1100mcA_UTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edt1100mcA_UTKeyReleased
        int nVal = 0;
        String strTyped = edt1100mcA_UT.getText();
        try { nVal = Integer.parseInt( strTyped); }
        catch( NumberFormatException ex) {  }
        lblValueUt1100.setText( String.format( "%.0f V", m_dbl_TUCoefficient_11 * nVal));
    }//GEN-LAST:event_edt1100mcA_UTKeyReleased

    private void edt1200mcA_UAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edt1200mcA_UAKeyReleased
        int nVal = 0;
        String strTyped = edt1200mcA_UA.getText();
        try { nVal = Integer.parseInt( strTyped); }
        catch( NumberFormatException ex) {  }
        lblValueUa1200.setText( String.format( "%.0f V", m_dbl_AUCoefficient_12 * nVal));
    }//GEN-LAST:event_edt1200mcA_UAKeyReleased

    private void edt1200mcA_UTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edt1200mcA_UTKeyReleased
        int nVal = 0;
        String strTyped = edt1200mcA_UT.getText();
        try { nVal = Integer.parseInt( strTyped); }
        catch( NumberFormatException ex) {  }
        lblValueUt1200.setText( String.format( "%.0f V", m_dbl_TUCoefficient_12 * nVal));
    }//GEN-LAST:event_edt1200mcA_UTKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1000mcA;
    private javax.swing.JButton btn1100mcA;
    private javax.swing.JButton btn1200mcA;
    private javax.swing.JButton btnNext;
    public javax.swing.JTextField edt1000mcA_UA;
    public javax.swing.JTextField edt1000mcA_UT;
    public javax.swing.JTextField edt1100mcA_UA;
    public javax.swing.JTextField edt1100mcA_UT;
    public javax.swing.JTextField edt1200mcA_UA;
    public javax.swing.JTextField edt1200mcA_UT;
    private javax.swing.JLabel lblEquUa1000;
    private javax.swing.JLabel lblEquUa1100;
    private javax.swing.JLabel lblEquUa1200;
    private javax.swing.JLabel lblEquUt1000;
    private javax.swing.JLabel lblEquUt1100;
    private javax.swing.JLabel lblEquUt1200;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1000mcA;
    private javax.swing.JLabel lblTitle1100mcA;
    private javax.swing.JLabel lblTitle1200mcA;
    private javax.swing.JLabel lblTitleUanode;
    private javax.swing.JLabel lblTitleUtubulation;
    private javax.swing.JLabel lblValueUa1000;
    private javax.swing.JLabel lblValueUa1100;
    private javax.swing.JLabel lblValueUa1200;
    private javax.swing.JLabel lblValueUt1000;
    private javax.swing.JLabel lblValueUt1100;
    private javax.swing.JLabel lblValueUt1200;
    // End of variables declaration//GEN-END:variables
}
